### PR TITLE
Prep for v0.0.5 tag

### PR DESCRIPTION
**Pull request by ericdill**
I am reasonably confident that these are the changes that are needed to add a whats_new section to our docs in preparation for the v0.0.5 tag. However, sphinx is not playing nicely with my laptop right now. If someone else wanted to confirm that these changes actually do work, I can get on with the v0.0.5 tag!

### CODE REVIEW

**Comment by ericdill** [comment]
Ok, apparently this actually is working fine if I remove all of the numpydoc files from /doc/sphinxext/ and let sphinx use numpydoc that is installed with `conda install numpydoc`

**Comment by ericdill** [comment]
@danielballan @tacaswell wasn't there an issue with some version of sphinx? Help me remember what that issue was and what version that problem occurs on?

**Comment by tacaswell** [comment]
They broke autosummary which is what makes the nice tables.

When it happened it was the latest version, but i don't remember the number.

**Comment by danielballan** [comment]
IIRC, you need 1.2.x (probably 1.2.3). The break occurred in 1.3.0.

**Comment by danielballan** [comment]
+1 on not bundling the extensions. That was a rookie mistake of mine; I was working off a bad example, didn't realize so much of those stuff was on PyPI. Consider cherry-picking #336 onto this PR.

**Comment by tacaswell** [comment]
Also +1 on removing extensions, mistake of mine that they ever were merged

**Comment by ericdill** [comment]
Should I remove **all** of the extensions?  As of now I just remove the numpydoc ones

**Comment by ericdill** [comment]
Everyone ok with me merging and tagging v0.0.5?

**Pull request merged**
