### PR TITLE
Move extract label function

### PR DESCRIPTION
**Pull request by sameera2004**

### CODE REVIEW

**Comment by sameera2004** [comment]
I wanted to move the extract_label_indices function from correlation.py to roi.py
 Because it better suited in that module

**Comment by ericdill** [comment]
Can you update scikit-xray-examples too?

https://github.com/scikit-xray/scikit-xray-examples/search?utf8=%E2%9C%93&q=extract_label_indices

**Comment by ericdill** [comment]
I think that this move makes sense and am :+1:  on it.  I will merge this once you update scikit-xray-examples

**Comment by ericdill** [comment]
Can you add an entry to "api_changes" https://github.com/scikit-xray/scikit-xray/tree/master/doc/api_changes for this api change

**Comment by sameera2004** [comment]
@ericdill added entry in the api changes ready for review

**Comment by sameera2004** [comment]
Thanks Tom

**Pull request merged**
